### PR TITLE
Add What Lies Between AutoSplitter

### PR DESCRIPTION
**Pull request by luna-dzx**
If you are adding or modifying an Auto Splitter, please fill out this checklist:
- [x] My Auto Splitter does not contain any malicious functionality and I'm entirely responsible for any damages myself. (Any kind of abuse in an Auto Splitter will result in an immediate ban.)
- [x] I am not replacing an existing Auto Splitter by a different author, or I have received permission from the author to replace the existing Auto Splitter.
- [x] The Auto Splitter has an open source license that allows anyone to fork and host it.

### CODE REVIEW

**Comment by just-ero** [comment]
I don't know how comfortable I feel merging this with the download code in there. @wooferzfg's call.

**Comment by wooferzfg** [comment]
Why do we need that download code?

**Comment by just-ero** [comment]
I presume it was left for testing to allow users to not be forced to download the helper library manually. This shouldn't apply anymore with the addition here though.

**Comment by luna-dzx** [comment]
I've removed the link, it wasn't necessary my bad

**Pull request merged**
