### PR TITLE
Update LiveSplit.AutoSplitters.xml

### PR DESCRIPTION
**Pull request by eroadhouse**
Changed LEGO Star Wars: The Complete Saga to updated AutoSplitter

If you are adding or modifying an Auto Splitter, please fill out this checklist:
- [X ] My Auto Splitter does not contain any malicious functionality and I'm entirely responsible for any damages myself. (Any kind of abuse in an Auto Splitter will result in an immediate ban.)
- [X ] I am not replacing an existing Auto Splitter by a different author, or I have received permission from the author to replace the existing Auto Splitter.
- [X ] The Auto Splitter has an open source license that allows anyone to fork and host it.

### CODE REVIEW

**Comment by just-ero** [comment]
@melodyfast Are you alright with this change?

**Comment by eroadhouse** [comment]
I don't know how active melody is on github at the current moment, but melody is aware that we are no longer using their autosplitter and haven't been for the past year or so. This new version in the PR also has a load remover implemented whereas melody's does not, so it needs to be changed even if melody doesn't respond. Saying this as a moderator for the game :)

**Comment by just-ero** [comment]
> so it needs to be changed even if melody doesn't respond

That's not really true. If they are active on GitHub, you could simply PR their repo and make your changes there. Or at least host a fork so that file history is preserved.

**Comment by eroadhouse** [comment]
I wasn't really talking about the repo, moreso just the actual update to the AutoSplitter since the one linked to melody's is outdated. Also was only really saying it since I have no idea how active melody is anymore. The last time they made a contribution was 6 months ago. I also know they'd be okay with the change here

**Comment by eroadhouse** [comment]
Also we don't want the new AutoSplitter on melody's repo

**Pull request merged**
