### PR TITLE
re2r Update LiveSplit.AutoSplitters.xml

### PR DESCRIPTION
**Pull request by VideoGameRoulette**
Resident Evil 2 2019 and Resident Evil 3 2020 scripts repo updated to new repo spoken with CursedToast and he approved this action and I will be maintaining the scripts going forward.

If you are adding or modifying an Auto Splitter, please fill out this checklist:
- [✓ ] My Auto Splitter does not contain any malicious functionality and I'm entirely responsible for any damages myself. (Any kind of abuse in an Auto Splitter will result in an immediate ban.)
- [ ✓] I am not replacing an existing Auto Splitter by a different author, or I have received permission from the author to replace the existing Auto Splitter.
- [✓ ] The Auto Splitter has an open source license that allows anyone to fork and host it.

### CODE REVIEW

**Comment by just-ero** [comment]
@cursedtoast Can you confirm you are alright with this change?

**Comment by just-ero** [comment]
I do question why these repos aren't forks of the original, which would preserve file history, but I suppose this is a personal choice.

**Comment by VideoGameRoulette** [comment]
just to let you know @cursedtoast no longer has access to his github account, you'd have to ask him on discord if you want any sort of reply

**Comment by just-ero** [comment]
> just to let you know @cursedtoast no longer has access to his github account, you'd have to ask him on discord if you want any sort of reply

Apologies, but it's not my burden to provide this proof, it's yours.

**Comment by VideoGameRoulette** [comment]
image
our conversation on discord

**Comment by just-ero** [comment]
Looks good! Are you still considering forking the original repo instead of creating a completely new one? To preserve the commit history like I mentioned? If so, I'll wait for you to do that before merging.

**Comment by VideoGameRoulette** [comment]
I could do that, i'll reply when complete

**Comment by VideoGameRoulette** [comment]
ok done :)

**Pull request merged**
