### PR TITLE
Updating UC4 & LL autosplitter W/Mattmatts permission

### PR DESCRIPTION
**Pull request by TheDementedSalad**
If you are adding or modifying an Auto Splitter, please fill out this checklist:
- [ x] My Auto Splitter does not contain any malicious functionality and I'm entirely responsible for any damages myself. (Any kind of abuse in an Auto Splitter will result in an immediate ban.)
- [ x] I am not replacing an existing Auto Splitter by a different author, or I have received permission from the author to replace the existing Auto Splitter.
- [ x] The Auto Splitter has an open source license that allows anyone to fork and host it.

### CODE REVIEW

**Comment by wooferzfg** [comment]
Just want to confirm that you received permission from the existing author to replace their Auto Splitter.

**Comment by TheDementedSalad** [comment]
Yeah, I recieved perms from Matt.

**Comment by just-ero** [comment]
That response is about as valuable as setting the check in the original PR message lol

**Comment by wooferzfg** [comment]
I disagree - some people fill out the checklist automatically without thinking enough about it, and I think it helps to double check.

**Pull request merged**
