### PR TITLE
Update avp2 urls and games

### PR DESCRIPTION
**Pull request by mitchell-merry**
If you are adding or modifying an Auto Splitter, please fill out this checklist:
- [x] My Auto Splitter does not contain any malicious functionality and I'm entirely responsible for any damages myself. (Any kind of abuse in an Auto Splitter will result in an immediate ban.)
- [x] I am not replacing an existing Auto Splitter by a different author, or I have received permission from the author to replace the existing Auto Splitter.
- [x] The Auto Splitter has an open source license that allows anyone to fork and host it.

### CODE REVIEW

**Comment by just-ero** [comment]
Someone correct me if I'm wrong, but changing the component URL to `Resources/*.dll` will break the component. I believe the file will also be *downloaded* into a `Resources` folder, which LiveSplit will not look for components in.

**Comment by mitchell-merry** [comment]
Oh strange. I'll just change it when I get a chance.

**Comment by mitchell-merry** [comment]
I assumed you weren't talking about something other than `Components` since others don't follow that: https://github.com/LiveSplit/LiveSplit.AutoSplitters/blob/824c282c60df7cffdd6098b3010664bcfc22b430/LiveSplit.AutoSplitters.xml#L2538

**Comment by wooferzfg** [comment]
> Someone correct me if I'm wrong, but changing the component URL to `Resources/*.dll` will break the component. I believe the file will also be *downloaded* into a `Resources` folder, which LiveSplit will not look for components in.

This isn't true. The files always end up in the `Components` folder, with the filename determined by the last part of the URL. See this code: https://github.com/LiveSplit/LiveSplit/blob/master/LiveSplit/LiveSplit.Core/Model/AutoSplitter.cs#L64

You might have been thinking of the update XMLs?

**Comment by wooferzfg** [comment]
@mitchell-merry Feel free to revert back to what you had before.

**Comment by mitchell-merry** [comment]
Ah, okay. I think I prefer it this way anyways. Thanks

**Pull request merged**
