### PR TITLE
LiveSplit.AutoSplitters.xml

### PR DESCRIPTION
**Pull request by TpRedNinja**
Update the tomb raider 2013 to now have autosplitter plus load remover keeping original guys credits so people know. Added autosplitter raw
added settings raw
added asl-help raw for the section so everything just works. Did do poll on discord to make sure everyone was okay with the change.

If you are adding or modifying an Auto Splitter, please fill out this checklist:
- [x] My Auto Splitter does not contain any malicious functionality and I'm entirely responsible for any damages myself. (Any kind of abuse in an Auto Splitter will result in an immediate ban.)
- [ ] I am not replacing an existing Auto Splitter by a different author, or I have received permission from the author to replace the existing Auto Splitter.
- [x] The Auto Splitter has an open source license that allows anyone to fork and host it.

### CODE REVIEW

**Comment by just-ero** [comment]
Asking @JMaynard24 to confirm this change here.

**Comment by TpRedNinja** [comment]
i have a picture of a poll from the tomb raider speedrun discord 
image

**Comment by just-ero** [comment]
This is obviously not the same as  
> I have received permission from the author to replace the existing Auto Splitter.

I am gathering you filled out this check list fraudulently? Is there a reason you felt compelled to lie?

**Comment by TpRedNinja** [comment]
> This is obviously not the same as
> 
> > I have received permission from the author to replace the existing Auto Splitter.
> 
> I am gathering you filled out this check list fraudulently? Is there a reason you felt compelled to lie?

wasn't intently trying to lie i figured getting permission from the community it was apart off was enough sense i couldnt get in contact in anyway shape or form with the orginal author but i will change it so i didnt have permission. Then you can do whatever ig.

**Pull request merged**
