### PR TITLE
Dead Space (2008): Auto Start and Split by chapter

### PR DESCRIPTION
**Pull request by ladamalina**
Add auto splitting functionality. Previous version supports manual splits only.

Tested by Ladamalina, MrKak0ss & Flower during [speedrun tournament](https://docs.google.com/spreadsheets/d/1OmmAI6xzEbfzowbimrp10qIV-i0MUHRPzarc_xwOY8s/edit?gid=634871480#gid=634871480) this autumn.

If you are adding or modifying an Auto Splitter, please fill out this checklist:
- [x] My Auto Splitter does not contain any malicious functionality and I'm entirely responsible for any damages myself. (Any kind of abuse in an Auto Splitter will result in an immediate ban.)
- [x] I am not replacing an existing Auto Splitter by a different author, or I have received permission from the author to replace the existing Auto Splitter.
- [x] The Auto Splitter has an open source license that allows anyone to fork and host it.

--- 

I am ready to add new auto splitter recort to XML if extending any functionality of existing splitters is strictly prohibited.

### CODE REVIEW

**Comment by wooferzfg** [comment]
Did you receive permission to replace the previous autosplitter from the original author?

**Comment by ladamalina** [comment]
No. So I have added a comment about it. Should I add a new splitter record to XML while existing splitter is manual actually?

> I am ready to add new auto splitter recort to XML if extending any functionality of existing splitters is strictly prohibited.

**Comment by wooferzfg** [comment]
No, you need to obtain permission

**Comment by ladamalina** [comment]
@Mattmatt10111 Hello! May I replace your ASL for Dead Space 2008 with updated version please?

We realize that current version provides only manual splitting during speedrun tournament this week. New version has been tested by at least 3 gamers and provides an accurate auto splitting by chapter.

--- 

@wooferzfg Thank you for clarifying

**Comment by Mattmatt10111** [comment]
I've been meaning to update the original Dead Space ASL for a while now but I didn't have access to the steam version. I do now and I also want to add support for the origin version even though I think they're the same but it's better to be safe than sorry. I'll try and get it done as soon as I can but I'd rather not have my ASL replaced if that's okay.

**Pull request closed without merging**
