### PR TITLE
Update LiveSplit.AutoSplitters.xml

### PR DESCRIPTION
**Pull request by StenIsMe**
Far Cry 3 Blood Dragon asl full rework

If you are adding or modifying an Auto Splitter, please fill out this checklist:
- [✓] My Auto Splitter does not contain any malicious functionality and I'm entirely responsible for any damages myself. (Any kind of abuse in an Auto Splitter will result in an immediate ban.)
- [✓] I am not replacing an existing Auto Splitter by a different author, or I have received permission from the author to replace the existing Auto Splitter.
- [✓] The Auto Splitter has an open source license that allows anyone to fork and host it.

### CODE REVIEW

**Comment by just-ero** [comment]
@AlexYeahNot Are you okay with this change?

**Comment by StenIsMe** [comment]
Discord_1vQvLrzgNW
"Well, do you mind if I replace the link to your asl in the AutoSplitters XML?"
"Yeah, I'm fine with that"

**Comment by StenIsMe** [comment]
@just-ero Alex has a problem with logining into GitHub, he will try to message here later this day if it's needed

**Comment by AlexYeahNot** [comment]
> @AlexYeahNot Are you okay with this change?

Yes, sure, vlad made greater version of AS, so yes, im okay with it

**Pull request merged**
