### PR TITLE
Update LiveSplit.AutoSplitters.xml

### PR DESCRIPTION
**Pull request by ru-mii**
Just some structural changes for my autosplitters.

If you are adding or modifying an Auto Splitter, please fill out this checklist:
- [X] My Auto Splitter does not contain any malicious functionality and I'm entirely responsible for any damages myself. (Any kind of abuse in an Auto Splitter will result in an immediate ban.)
- [X] I am not replacing an existing Auto Splitter by a different author, or I have received permission from the author to replace the existing Auto Splitter.
- [X] The Auto Splitter has an open source license that allows anyone to fork and host it.

### CODE REVIEW

**Comment by just-ero** [comment]
I don't view this as the best idea. This will make these scripts overwrite each other when a different game you support is chosen. Are you sure you want to make this change? I personally highly discourage this structure.

**Comment by ru-mii** [comment]
> I don't view this as the best idea. This will make these scripts overwrite each other when a different game you support is chosen. Are you sure you want to make this change? I personally highly discourage this structure.

Overwrite? In what way?

**Comment by wooferzfg** [comment]
They all have the name `script.asl`, which is what's used when LiveSplit downloads the script

**Comment by ru-mii** [comment]
Ahh... I see what you mean now, let's close this one and I'll remake my idea slightly, thanks for the heads up lads I honestly didn't even think about it.

**Pull request closed without merging**
