### PR TITLE
Added Splinter Cell: Chaos Theory AutoSplitter

### PR DESCRIPTION
**Pull request by DistProg**
Added SCCT autosplitter with load removal functionality.

If you are adding or modifying an Auto Splitter, please fill out this checklist:
- [X] My Auto Splitter does not contain any malicious functionality and I'm entirely responsible for any damages myself. (Any kind of abuse in an Auto Splitter will result in an immediate ban.)
- [X] I am not replacing an existing Auto Splitter by a different author, or I have received permission from the author to replace the existing Auto Splitter.
- [X] The Auto Splitter has an open source license that allows anyone to fork and host it.

### CODE REVIEW

**Comment by just-ero** [comment]
This game is already supported by @Dalet's [`UnrealLoads`](https://github.com/Dalet/LiveSplit.UnrealLoads) component ([L3731](https://github.com/LiveSplit/LiveSplit.AutoSplitters/blob/d5d8fdd710beeb752afdb9c3d19b63872aaec04e/LiveSplit.AutoSplitters.xml#L3731)). Please talk to them about replacing it.

**Comment by just-ero** [comment]
After this commit, is your second checkbox true anymore? Have you asked @Dalet for permission?

**Comment by Dalet** [comment]
We just talked. I support the replacement.

**Comment by DistProg** [comment]
Yes. I can confirm that Dalet and I talked before I made the last commit.

**Pull request merged**
