### PR TITLE
Removed the Minecraft: Java Edition component

### PR DESCRIPTION
**Pull request by Jorkoh**
I can no longer maintain this component and the community is transitioning into new timing methods so I'm leaving the game up for grabs.

### CODE REVIEW

**Comment by CryZe** [comment]
I'm not sure if removing it entirely rather than marking it as up for grabs in some way makes sense.

**Comment by Jorkoh** [comment]
Feel free to handle it as you see fit as long as it doesn't require my participation. I don't want to be involved in the community.

All the component did was read a value from a .json file. There are multiple standalone open source working alternatives in the community so it should be trivial for anyone to write their own implementation and take ownership of project.

**Comment by wooferzfg** [comment]
I think it's fine to just remove it since the links are broken now.

**Comment by CryZe** [comment]
@Jorkoh Could you kindly provide us a backup of those files (and possibly source code)? I'm totally fine with you not wanting to be involved anymore, but it would be nice if we could still host it in some way. Or maybe you could link one of those alternatives?

**Comment by Jorkoh** [comment]
[This is a popular alternative for those in Mac/Linux](https://github.com/NinjaSnail1080/mc-universal-in-game-timer) and this is a perhaps [simpler implementation](https://github.com/bleach86/MCtimer).

It boils down to:

1. Locate the saves folder, by default `C:\Users\<username>\AppData\Roaming\.minecraft\saves`
2. Find the active world in the saves folder, commonly the most recent folder by creation date.
3. In the world folder there's a stats folder containing a stats json file for each player, since the runs are single player there's no confussion. The path will look like this: `.minecraft\saves\<world_name>\stats\<player_id>.json`
4. Read the INT value with key `minecraft:play_one_minute` or `stat.playOneMinute` Only one of them will be present depending on the game's version.
5. Divide that value by 20 to translate from game ticks into seconds and display the value.

**Comment by CryZe** [comment]
Could you kindly allow us to host a version of your timer in the meantime? This is too disruptive that I'd like to at least provide something in the meantime. I already don't have much time today, but I now need to spend it on fixing this instead. Please don't make this unnecessarily hard on us.

**Comment by Jorkoh** [comment]
Sorry but I fail to see why it would be your responsability to fix this and I don't understand how it can be disruptive. I never expected this removal to affect LiveSplit maintainers since I always emphasized the difference between community contributed add-ons and the original project.

I expect the leaderboard's moderation team, wich has plenty of technologically capable members with more field knowledge than either of us, to provide a solution if it's actually needed. IGT timers are just a convenience, not a requirement. In the meantime they can use alternative IGT timers, easily check the value manually or retime their runs from video.

I have clearly expressed my wish to not have my implementation used any longer but at the end of the day it was a contribution to a MIT project so I can't (and won't try to) stop anyone. I don't keep backups of them but I imagine you can just ask any runner for a copy of them from their `Components` folder. Again, sorry for the inconveniences.

**Pull request merged**
