### PR TITLE
Added autosplitter for Another Crab's Treasure

### PR DESCRIPTION
**Pull request by Jarlyk**
If you are adding or modifying an Auto Splitter, please fill out this checklist:
- [ X] My Auto Splitter does not contain any malicious functionality and I'm entirely responsible for any damages myself. (Any kind of abuse in an Auto Splitter will result in an immediate ban.)
- [ X] I am not replacing an existing Auto Splitter by a different author, or I have received permission from the author to replace the existing Auto Splitter.
- [ X] The Auto Splitter has an open source license that allows anyone to fork and host it.

### CODE REVIEW

**Comment by just-ero** [comment]
This autosplitter makes incredibly inproper use of asl-help. I would not recommend this be merged in its current state.

**Comment by Jarlyk** [comment]
I appreciate that my implementation isn't a clean use of aslhelp (as it's based on what I did for GRIME, which required late-binding some of the static classes, which wasn't required for this game), but it's functional and it was something I could put together quickly as a favor for a friend.  I don't believe there's anything harmful about the way the code is written and it's been tested by multiple runners, who are happy with its performance.

**Comment by just-ero** [comment]
Exposing and accessing the `mono` instance from `TryLoad` is undefined behavior and strongly advised against. I cannot merge this in good conscience the way it is.

**Comment by Jarlyk** [comment]
I removed capturing of the mono instance in the TryLoad, as this splitter doesn't actually require it and was just a leftover from GRIME, where it was needed to re-read the static method tables due to some classes being loaded only after file select was complete.  Is that sufficient to resolve your concerns?

**Comment by just-ero** [comment]
Capturing all of the other classes is also unnecessary and I have trouble understanding why you chose to do so. I have a more concise version of the splitter at [this Gist](https://gist.github.com/just-ero/c3937e0c9336e452d6fc9bff8a4a7e05). Feel free to copy without credit.

For your information, you have a mistake in your setting for `Curdled Carbonara Conoisseur Defeated`. Its ID should be `800`.

**Comment by Jarlyk** [comment]
Thanks, seeing your cleaner implementation is actually quite helpful.  And also thanks for pointing out the mistake on one of the settings.  I wasn't aware the settings could be specified via XML like that and for this particular game, including the id information as part of the setting name makes a lot of sense.  I may switch to your implementation later once I can get some runners to test it.

**Pull request merged**
