### PR TITLE
Update LiveSplit.AutoSplitters.xml

### PR DESCRIPTION
**Pull request by Siedemnastek**
If you are adding or modifying an Auto Splitter, please fill out this checklist:
- [Yes] My Auto Splitter does not contain any malicious functionality and I'm entirely responsible for any damages myself. (Any kind of abuse in an Auto Splitter will result in an immediate ban.)
- [Yes] I am not replacing an existing Auto Splitter by a different author, or I have received permission from the author to replace the existing Auto Splitter.
- [Yes] The Auto Splitter has an open source license that allows anyone to fork and host it.

### CODE REVIEW

**Comment by just-ero** [comment]
@melodyfast Are you alright with these changes?

**Comment by Siedemnastek** [comment]
> @melodyfast Are you alright with these changes?

Sorry about the wait, I've tried to reach out to them, but Melody has been inactive in the LEGO community for months now, their autosplitter I'm replacing here was broken, I hope that's alright

**Comment by just-ero** [comment]
Can you show any proof of having talked to the author? After all, you checked that requirement.

**Comment by Siedemnastek** [comment]
image

My latest DMs with them

**Comment by wooferzfg** [comment]
In the future, please be upfront about not having received permission from the author in the PR description checklist

In this case, I think this is OK to merge, since the previous auto splitter is broken, and the original author hasn't been replying on Discord or GitHub.

**Comment by Siedemnastek** [comment]
Alright, thanks. And sorry for the mess, I just thought I'd be easily able to contact the author since I had in the past, so I'll make sure to not state it before next time

**Pull request merged**
