### PR TITLE
At World's End ASL.xml

### PR DESCRIPTION
**Pull request by LeonSReckon**
If you are adding or modifying an Auto Splitter, please fill out this checklist:
- [X] My Auto Splitter does not contain any malicious functionality and I'm entirely responsible for any damages myself. (Any kind of abuse in an Auto Splitter will result in an immediate ban.)
- [X] I am not replacing an existing Auto Splitter by a different author, or I have received permission from the author to replace the existing Auto Splitter.
- [X] The Auto Splitter has an open source license that allows anyone to fork and host it.

### CODE REVIEW

**Comment by just-ero** [comment]
There is already an auto splitter for this game present in the list, made by @Monstruos.

**Comment by LeonSReckon** [comment]
The moderator didn't tell me that?
Maybe it's another game in the serious. I'll check

**Comment by LeonSReckon** [comment]
Looks like that Monstrous guy made the autosplitter but didn't tell anyone about it because the Moderator of the leaderboard doesn't know anything about this or otherwise he wouldn't have commissioned me to make the splitter

**Comment by LeonSReckon** [comment]
image - Copie

**Comment by wooferzfg** [comment]
Please reach out to the original author and get permission to replace their autosplitter.

**Comment by LeonSReckon** [comment]
He doesn't have any social media attach to his profile neither here nor on SpeedRun.com!

**Comment by Monstruos** [comment]
In the resources of the game on speedrun.com I wrote about splitter)

**Comment by wooferzfg** [comment]
Please replace the existing Auto Splitter in this PR

**Comment by LeonSReckon** [comment]
Done

**Pull request merged**
