### PR TITLE
Update TAG

### PR DESCRIPTION
**Pull request by permanentdaylightt**
If you are adding or modifying an Auto Splitter, please fill out this checklist:
- [X] My Auto Splitter does not contain any malicious functionality and I'm entirely responsible for any damages myself. (Any kind of abuse in an Auto Splitter will result in an immediate ban.)
- [X] I am not replacing an existing Auto Splitter by a different author, or I have received permission from the author to replace the existing Auto Splitter.
- [X] The Auto Splitter has an open source license that allows anyone to fork and host it.

### CODE REVIEW

**Comment by wooferzfg** [comment]
Did you receive permission to replace the autosplitter?

**Comment by permanentdaylightt** [comment]
star — Today at 6:03 PM
hey hello
ive js updated the tag autosplitter
can i get permission to update it
well i js formatted it and replaced error thingy
@Altafen#6776
Altafen#6776 — Today at 8:11 PM
Hi
Little busy today but I can give you push or accept a pr later
star — Today at 8:48 PM
lol
im gonna submit it to
livesplit repo
Altafen#6776 — Today at 8:49 PM
O cool that works

**Comment by just-ero** [comment]
Can @BR- please confirm here as well?

**Comment by permanentdaylightt** [comment]
let me dm them too

**Comment by permanentdaylightt** [comment]
its their git account

**Comment by permanentdaylightt** [comment]
who owns the repo?
they need to respond so
Altafen#6776 — 09/13/2024 8:53 PM
I am @BR- on github 
Really busy today though can I get to this later tonight or tomorrow

**Comment by permanentdaylightt** [comment]
can anyone look on this?

**Comment by just-ero** [comment]
Still waiting for @BR- to confirm here.

**Comment by BR-** [comment]
Oops, this slipped my mind. I haven't been active in Tag for years. They can replace it.

**Pull request closed without merging**
