### PR TITLE
Update LiveSplit.AutoSplitters.xml

### PR DESCRIPTION
**Pull request by Gemr007**
If you are adding or modifying an Auto Splitter, please fill out this checklist:
- [✓ ] My Auto Splitter does not contain any malicious functionality and I'm entirely responsible for any damages myself. (Any kind of abuse in an Auto Splitter will result in an immediate ban.)
- [✓ ] I am not replacing an existing Auto Splitter by a different author, or I have received permission from the author to replace the existing Auto Splitter. (I replace an old Load Remover, i wrote a better, so I think a have permission)
- [ ✓] The Auto Splitter has an open source license that allows anyone to fork and host it.

### CODE REVIEW

**Comment by Jujstme** [comment]
I'm fine with the replacement. Although, next time, it would've been appreciated if I was asked first.

Keep in mind you're expressly stating that you "received permission from the author to replace the existing Auto Splitte".

**Comment by just-ero** [comment]
Future changes by this user will be under much more scrutiny. Do not lie when you fill out this check box.

I would like a leaderboard moderator to also confirm this change is supported by the community.

**Comment by Gemr007** [comment]
изображение

**Comment by just-ero** [comment]
Please ask a moderator to confirm this change here in this discussion. The link you posted does not confirm the replacement.

**Comment by duanejones** [comment]
yo, mod here.  I am confused.  I have not needed to approve autosplitter uploads in the past for this game, wolfenstein 2009, or any of the other games I mod.  Is Gemr007 doing something out of the ordinary?  Wolfenstein has a very small number of runners and it looks like he's trying to update his own previously uploaded autosplitter?  If that is not the case, I am mistaken and please correct me.

**Comment by duanejones** [comment]
Okay I'm seeing that jujstme has an autosplitter for wolfenstein that doesn't seem to be listed on the src resource page for wolfenstein.  Why is gemr007 trying to replace someone elses autosplitter?  Why not just upload/update his own?

**Comment by just-ero** [comment]
This XML file acts as a database for integrated autosplitters that can be enabled from the splits editor, tying the autosplitter and its settings to a split file instead of a layout file.

It is generally accepted to replace another author's autosplitter when the new one adds more or better functionality and/or the previous author no longer cares to maintain the autosplitter on their account.

However, since this user flat-out lied in their PR message, I wanted a word from an actual community moderator on the matter. Gemr007 has unfortunately waived their right to add or change entries in this list without community approval.

**Comment by duanejones** [comment]
Roger.  Thank you for you explanation and for all y'alls committment to the vetting process.  I appreciate it.

**Pull request merged**
