### PR TITLE
update resource links and add devastation

### PR DESCRIPTION
**Pull request by mitchell-merry**
If you are adding or modifying an Auto Splitter, please fill out this checklist:
- [x] My Auto Splitter does not contain any malicious functionality and I'm entirely responsible for any damages myself. (Any kind of abuse in an Auto Splitter will result in an immediate ban.)
- [x] I am not replacing an existing Auto Splitter by a different author, or I have received permission from the author to replace the existing Auto Splitter.
- [x] The Auto Splitter has an open source license that allows anyone to fork and host it.

### CODE REVIEW

**Comment by just-ero** [comment]
It's generally good GitHub etiquette to split this into separate PRs.

**Comment by mitchell-merry** [comment]
Why?

**Comment by just-ero** [comment]
The changes are unrelated. Different changes usually go into different PRs.

**Comment by mitchell-merry** [comment]
I figured it didn't really matter here

**Pull request merged**
