### PR TITLE
Added autosplitter for Beton Brutal based on in-game height

### PR DESCRIPTION
**Pull request by CubeSkyy**
If you are adding or modifying an Auto Splitter, please fill out this checklist:
- [ ✓] My Auto Splitter does not contain any malicious functionality and I'm entirely responsible for any damages myself. (Any kind of abuse in an Auto Splitter will result in an immediate ban.)
- [ ✓] I am not replacing an existing Auto Splitter by a different author, or I have received permission from the author to replace the existing Auto Splitter.
- [ ✓] The Auto Splitter has an open source license that allows anyone to fork and host it.

### CODE REVIEW

**Comment by just-ero** [comment]
I do not feel comfortable with merging this auto splitter into the XML. The script's `exit` block is very questionable.

The block in question is as follows:
```cs
exit
{
    timer.CurrentPhase = TimerPhase.NotRunning;
}
```

This code does have the desired effect of resetting the timer, but does ***not*** save the splits. This is very bad for the users and their times, run histories, and user experience.

If you truly must have this feature, please consider something like this instead;
```cs
startup
{
    vars.TimerModel = new TimerModel { CurrentState = timer };
}

reset
{
    // Must contain any code at all for `settings.ResetEnabled` to become available.
    return false;
}

exit
{
    if (settings.ResetEnabled)
        vars.TimerModel.Reset();
}
```

This *will* save all splits and times.

**Comment by CubeSkyy** [comment]
Thank you for the response ero.
I'm updating the script to use the TimerModel.Reset instead. 
I just don't get the comment in the reset block. I think my reset logic can stay the same and just update the startup/exit blocks, no?

**Comment by just-ero** [comment]
> I think my reset logic can stay the same and just update the startup/exit blocks, no?

Yes, it was just to illustrate.

**Comment by CubeSkyy** [comment]
Alright, I updated the script to use TimerModel instead, when you have time, take a look again

**Comment by just-ero** [comment]
Why did you do that instead of addressing the open PR?

**Pull request merged**
