### PR TITLE
Added IGT for Spark 3

### PR DESCRIPTION
**Pull request by skewbmaster**
If you are adding or modifying an Auto Splitter, please fill out this checklist:
- [X] My Auto Splitter does not contain any malicious functionality and I'm entirely responsible for any damages myself. (Any kind of abuse in an Auto Splitter will result in an immediate ban.)
- [X] I am not replacing an existing Auto Splitter by a different author, or I have received permission from the author to replace the existing Auto Splitter.
- [X] The Auto Splitter has an open source license that allows anyone to fork and host it.

### CODE REVIEW

**Comment by wooferzfg** [comment]
You shouldn't be modifying the pull request template.

**Comment by just-ero** [comment]
What's going on here? Why are you editing and adding files to this repo that don't actually have anything to do with the auto splitter?

**Comment by skewbmaster** [comment]
Sorry but I'm just not sure what I'm supposed to be doing for the PR, is the xml the only thing you change?

**Comment by just-ero** [comment]
> Sorry but I'm just not sure what I'm supposed to be doing for the PR, is the xml the only thing you change?

Yes, that is all you do.

**Pull request merged**
