### PR TITLE
Added autosplitting and blackscreen removal to Sekiro

### PR DESCRIPTION
**Pull request by FrankvdStam**
If you are adding or modifying an Auto Splitter, please fill out this checklist:
- [X] My Auto Splitter does not contain any malicious functionality and I'm entirely responsible for any damages myself. (Any kind of abuse in an Auto Splitter will result in an immediate ban.)
- [X] I am not replacing an existing Auto Splitter by a different author, or I have received permission from the author to replace the existing Auto Splitter.
- [X] The Auto Splitter has an open source license that allows anyone to fork and host it.

### CODE REVIEW

**Comment by NoTeefy** [comment]
@FrankvdStam do you have the authorization by B3 or the community to change the script?

**Comment by FrankvdStam** [comment]
@NoTeefy I don't know who RefinedHornet is. I talked to B3LYP, who made the original plugin, and the community of this game + its verifiers have been testing it for a couple weeks now. The verifiers asked me this morning to replace the OG plugin.

**Comment by FrankvdStam** [comment]
Don't take my word for it, ask them yourself in the discord https://discord.gg/AJBaCAVC

**Comment by NoTeefy** [comment]
> @NoTeefy I don't know who RefinedHornet is. I talked to B3LYP, who made the original plugin, and the community of this game + its verifiers have been testing it for a couple weeks now. The verifiers asked me this morning to replace the OG plugin.

RefinedHornet apparently made an update to B3's script and got B3's permission. Hence why I was asking if you got permission from Hornet as that's usually how we handle it (since Hornet is the current repository host).
If it was verified and accepted by the community I'm fine with merging it.
Just wanted to make sure as it's a bigger title and we had some problems with people swapping repositories over without getting permission by the communities before.

**Pull request merged**
