### PR TITLE
Add Component for Trackmania and Trackmania Club Campaigns

### PR DESCRIPTION
**Pull request by GreepTheSheep**
If you are adding or modifying an Auto Splitter, please fill out this checklist:
- [x] My Auto Splitter does not contain any malicious functionality and I'm entirely responsible for any damages myself. (Any kind of abuse in an Auto Splitter will result in an immediate ban.)
- [x] I am not replacing an existing Auto Splitter by a different author, or I have received permission from the author to replace the existing Auto Splitter.
- [x] The Auto Splitter has an open source license that allows anyone to fork and host it.

### CODE REVIEW

**Comment by just-ero** [comment]
I would highly recommend not using that as your download URL. You're gonna have to change it every single time you release a new version.

**Comment by GreepTheSheep** [comment]
I added a script on the Openplanet plugin (a plugin that integrates this component) that autoupdate the component if a new update is available thanks to GitHub API, should be fine

**Comment by just-ero** [comment]
How do you reckon that's gonna change the link in this file? Or do you not plan on changing the release version numbers (`1.8.20-custom` right now).

**Comment by GreepTheSheep** [comment]
Does LiveSplit force to download the version if we replace with a new one? If it is the case I will create a route from my website to give the last version

**Comment by just-ero** [comment]
The download is done via the link you specify in the `<URL>` tag. Since you are specifying a version-specific URL in your PR (`~/releases/download/1.8.20-custom/LiveSplit.Server.dll`), this will download a wrong version as soon as you publish an update with a different version ID (since the URL will not be the same).

Additionally, the file name (`LiveSplit.Server.dll`) is gonna cause massive issues. The LiveSplit.Server component is not meant to be overwritten, and because you're doing this, users will be completely unable to use the base LiveSplit.Server from their Components folder (files of the same name do not show up in the Layout Editor).

Pinging @wooferzfg to confirm this suspicion. Will close this PR if correct.

**Comment by GreepTheSheep** [comment]
> this will download a wrong version as soon as you publish an update with a different version ID

Ok so I just need to create a route on my website that redirects to the .dll file if it's okay?

> users will be completely unable to use the base LiveSplit.Server from their Components folder

That's understandable, I need to change the name of that

**Comment by just-ero** [comment]
> Ok so I just need to create a route on my website that redirects to the .dll file if it's okay?

That sounds fine, but I would suggest looking into hosting it on GitHub still. Look at how other components do it.

I'm honestly not quite sure if this will work as a component *at all* through this XML. Might want to wait for woofer to chime in.

**Comment by NoTeefy** [comment]
> > this will download a wrong version as soon as you publish an update with a different version ID
> 
> Ok so I just need to create a route on my website that redirects to the .dll file if it's okay?
> ...
@GreepTheSheep @just-ero 
Don't reimplement the wheel. Github already has support for that: [https://github.com/GreepTheSheep/LiveSplit.Server/releases/latest/download/LiveSplit.Server.dll](https://github.com/GreepTheSheep/LiveSplit.Server/releases/latest/download/LiveSplit.Server.dll)
Just make sure to change it to this URL and to always provide a "LiveSplit.Server.dll" with each release.
The rest should be handled by LiveSplit.

Best regards

**Comment by NoTeefy** [comment]
> > this will download a wrong version as soon as you publish an update with a different version ID
> 
> Ok so I just need to create a route on my website that redirects to the .dll file if it's okay?
> ...

@GreepTheSheep @just-ero 
Don't reimplement the wheel. Github already has support for that: [https://github.com/GreepTheSheep/LiveSplit.Server/releases/latest/download/LiveSplit.Server.dll](https://github.com/GreepTheSheep/LiveSplit.Server/releases/latest/download/LiveSplit.Server.dll)
Just make sure to change it to this URL and to always provide a "LiveSplit.Server.dll" with each release.
The rest should be handled by LiveSplit.

Best regards

**Comment by NoTeefy** [comment]
> > this will download a wrong version as soon as you publish an update with a different version ID
> 
> Ok so I just need to create a route on my website that redirects to the .dll file if it's okay?
> ...

@GreepTheSheep @just-ero 
Don't reinvent the wheel. Github already has support for that: [https://github.com/GreepTheSheep/LiveSplit.Server/releases/latest/download/LiveSplit.Server.dll](https://github.com/GreepTheSheep/LiveSplit.Server/releases/latest/download/LiveSplit.Server.dll)
Just make sure to change it to this URL and to always provide a "LiveSplit.Server.dll" with each release.
The rest should be handled by LiveSplit.

Best regards

**Comment by GreepTheSheep** [comment]
weird, I tried this url before but it returned me a 404. but okay this works. But I need to rebuild a new version of this component with the name changed to not confuse. Will update this PR asap

**Comment by just-ero** [comment]
> @GreepTheSheep @just-ero 
> Don't reinvent the wheel. Github already has support for that: [...]

Didn't suggest this because I wasn't entirely sure if it worked. /shrug

**Comment by NoTeefy** [comment]
> weird, I tried this url before but it returned me a 404. but okay this works. But I need to rebuild a new version of this component with the name changed to not confuse. Will update this PR asap

You probably tried to just replace the tag with "latest" which won't work. Check the difference in the urls:
- https://github.com/GreepTheSheep/LiveSplit.Server/releases/download/1.8.20-custom/LiveSplit.Server.dll
- https://github.com/GreepTheSheep/LiveSplit.Server/releases/latest/download/LiveSplit.Server.dll
To make it work, you need to add latest before the download directive and get rid of the release tag itself.

**Comment by GreepTheSheep** [comment]
Well we learned something new 😄

**Comment by GreepTheSheep** [comment]
@just-ero Updated!

**Pull request merged**
