### PR TITLE
Update LiveSplit.AutoSplitters.xml for Trackmania Games

### PR DESCRIPTION
**Pull request by Rastats**
• Added Trackmania (2020)
• Added Trackmania Category Extensions
• Added TrackMania Turbo VR Experience
• Updated link for TrackMania Turbo autosplitter

If you are adding or modifying an Auto Splitter, please fill out this checklist:
- [x] My Auto Splitter does not contain any malicious functionality and I'm entirely responsible for any damages myself. (Any kind of abuse in an Auto Splitter will result in an immediate ban.)
- [x] I am not replacing an existing Auto Splitter by a different author, or I have received permission from the author to replace the existing Auto Splitter.
- [x] The Auto Splitter has an open source license that allows anyone to fork and host it.

### CODE REVIEW

**Comment by wooferzfg** [comment]
Did you get permission to replace the existing autosplitter?

**Comment by Rastats** [comment]
Hey the autosplitter is the same as before with one extra option to split only if you beat the author medal on a track.
The same people remain credited on the Edit Splits window.

Sent from Proton Mail mobile

-------- Original Message --------

**Comment by just-ero** [comment]
That's not really getting permission.

@Voyager006 Do you agree with these changes?

**Comment by Voyager006** [comment]
Hi! Sorry for the late reply. @Rastats has messaged me earlier and the changes are good. I grant permission to go forward and replace the current autosplitter with the new fork.

**Pull request merged**
