### PR TITLE
Update TR2 splitter

### PR DESCRIPTION
**Pull request by MidgeOnGithub**
Failed to reach original script author for updates or approvals (last update ~ 3.5 years ago), so we created a new component from scratch. Supports FG, IL, and deathruns for all leaderboard-approved PC game versions.

If you are adding or modifying an Auto Splitter, please fill out this checklist:
- [X] My Auto Splitter does not contain any malicious functionality and I'm entirely responsible for any damages myself. (Any kind of abuse in an Auto Splitter will result in an immediate ban.)
- [X] I am not replacing an existing Auto Splitter by a different author, or I have received permission from the author to replace the existing Auto Splitter.
- [X] The Auto Splitter has an open source license that allows anyone to fork and host it.

### CODE REVIEW

**Comment by NoTeefy** [comment]
@MidgeOnGithub please add an open-source license to the repository (or the folder of your splitter).

**Comment by MidgeOnGithub** [comment]
> @MidgeOnGithub please add an open-source license to the repository (or the folder of your splitter).
MIT license is in the repo now. Thanks for the quick action.

**Comment by rtrger** [comment]
This hasn't been merged properly for some reason. Should we do a new pull request?

**Comment by Voxelse** [comment]
It seems that this PR has been unintentionally reverted in the next PR. #381 
Unfortunately yes, you have to do a new pull request.

**Pull request merged**
